M48
; DRILL file {KiCad 9.0.4} date 2026-03-27T14:05:24+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-27T14:05:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X24.625Y-19.5
X24.625Y-22.04
X34.5Y-20.32
X34.5Y-29.0
X40.64Y-20.32
X40.64Y-29.0
T2
X48.26Y-20.32
M30
